# fly.toml app configuration file generated for rough-morning-619 on 2023-06-13T16:04:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-morning-619"
primary_region = "arn"

[env]
  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
